// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-09-29 16:36:24

package com.mpaas.demo.rpc;

import com.alipay.mobile.framework.service.ext.annotation.CheckLogin;
import com.alipay.mobile.framework.service.annotation.OperationType;
import com.alipay.mobile.framework.service.annotation.SignCheck;


public interface CatPictureClient {


    @SignCheck
    @OperationType("com.cat.request")
    public String v1ImagesSearchGet ();


}